feat(po-dynamic): adiciona classes para espaçamento após o campo
po-ui/po-style pull request #158
Opened 2020-09-19 19:37 UTC by likid

Novas classes para funcionar em conjunto com a issue 585 no po-angular

Estas novas classes são necessárias para que a nova feature funcione

2020-09-25 18:55 UTC, jhosefmarks commented
As classes de offset já não atendem a necessidade?

2020-10-14 13:49 UTC, jhonyeduardo commented
Bom dia @likid 

Alguma novidade?

Conforme Jhosef comentou, temos classes offset, você pode verificar em nosso portal os exemplos: https://po-ui.io/guides/grid-system

2020-10-14 13:57 UTC, likid commented
@jhonyeduardo @jhosefmarks somente a classe offset não há como fazer a implementação da issue 585 no po-angular, porque senão o campo que você estará querendo criar espaços em branco na direita para "empurrar" os outros campos para o lado, ficaria indo para a direita também, então o offset empura para o lado (direito) e o pull puxa novamente para a esquerda, dessa forma fica o espaçamento desejado a direita do campo.
Foi dessa forma que consegui implementar copiando o componente po-dynamic-form e customizando ele localmente em outro projeto meu.

2020-11-24 19:55 UTC, jhosefmarks commented on src/css/commons/po-grid-system/po-grid-system-pull.css
> +    right: 8.33333333%;
Se você usar a propriedade right, vou vai "empurrar" o item de acordo com o pai (resumidamente falando), e o que você precisa é empurrar os itens que vem depois do elemento.

Use a propriedade margin-right.

2020-11-24 19:55 UTC, jhosefmarks commented on src/css/commons/po-grid-system/po-grid-system.css
> +  position: relative;
Usando o margin-right, não precisa dessa alteração.

2020-11-24 20:00 UTC, jhosefmarks commented on src/css/commons/po-grid-system/po-grid-system.css
> +  position: relative;
Usando o margin-right, não precisa dessa alteração.

2020-11-24 20:01 UTC, jhosefmarks requested changes

2020-11-24 20:01 UTC, jhosefmarks commented on src/css/commons/po-grid-system/po-grid-system-pull.css
> +    right: 8.33333333%;
Se você usar a propriedade right, vou vai "empurrar" o item de acordo com o pai (resumidamente falando), e o que você precisa é empurrar os itens que vem depois do elemento.

Use a propriedade margin-right.

2020-11-24 20:01 UTC, jhosefmarks commented on src/css/commons/po-grid-system/po-grid-system.css
> +  position: relative;
Usando o margin-right, não precisa dessa alteração.

2021-03-03 14:55 UTC, likid commented on src/css/commons/po-grid-system/po-grid-system.css
> +  position: relative;
Jhosef, refiz os testes e será necessário utilizar o position: relative e o right:, tratando somente com margin-right: e sem o position:relative, não ocorre o efeito esperado pela melhoria.

2021-03-05 17:40 UTC, jhonyeduardo approved these changes

2021-03-07 23:53 UTC, jhosefmarks approved these changes

2021-03-08 00:02 UTC, merged