Ani textarea/dthf UI 5514
po-ui/po-style pull request #278
Opened 2022-01-20 13:25 UTC by jcorrea97

2022-01-30 15:41 UTC, alinelariguet commented
**O commit:**
```
refactor(textarea): remove variáveis de customização de cores 

Remove variáveis de customização para compatibilidade com o `@animaliads/ani-textarea`:
 - `color-textarea-text-error`.

Fixes DTHFUI-5514

BREAKING CHANGE: remove variáveis de customização de cores

Remove variáveis para compatibilidade com `@animaliads/ani-textarea` e melhorias
de acessibilidade, não sendo mais possível a customização. são elas:

 - `color-textarea-text-error`: customização da cor do texto quando ocorre erro no componente.
```
 
 **Não deve ter o breaking change já que essa variável não era utilizada anteriormente.**

**Sugestão de mensagem:**
 
```
refactor(textarea): remove variável não utilizada
Remove variável de cor não utilizada `color-textarea-text-error`.

Fixes DTHFUI-5514
 
```

2022-01-30 15:43 UTC, alinelariguet commented
**O commit:**

```
refactor(textarea): remove classe de validação 

Remove classe de validação do componente textarea

Fixes DTHFUI-5514
```

**não deve se referir ao textarea:**

**Sugestão de mensagem:**

```
refactor(input): remove seletor de validação do po-textarea
Remove seletor css de validação do componente textarea do css do po-input.

Fixes DTHFUI-5514
```

2022-01-30 15:44 UTC, alinelariguet requested changes
Favor alterar mensagens de commit, conforme descrito nos comentários.

2022-01-31 12:01 UTC, rafaellmarques approved these changes

2022-01-31 12:20 UTC, brunoromeiro approved these changes

2022-01-31 18:45 UTC, alinelariguet approved these changes

2022-01-31 18:45 UTC, merged