feat(switch): aplica estilo definido pelo DS
po-ui/po-style pull request #332
Opened 2022-08-11 21:23 UTC by rafaellmarques

Aplicação de novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.

Fixes DTHFUI-6352

2022-08-16 12:54 UTC, jhosefmarks submitted a review, later dismissed

2022-08-16 13:26 UTC, brunoromeiro approved these changes

2022-08-19 00:41 UTC, alinelariguet commented
Necessário ajustar o app do CDN

2022-08-19 00:47 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-color-label: var(--color-neutral-dark-70);
incluir comentário de deprecated para as variáveis de customizações já existentes

2022-08-19 01:00 UTC, alinelariguet commented
Ficou desalinhado no po-page-login:
![Screen Shot 2022-08-18 at 22 00 30](https://user-images.githubusercontent.com/42390783/185520081-01a5fb09-314d-4f45-bd9c-b5632fb10702.png)

2022-08-19 01:02 UTC, alinelariguet commented
Ajustar o app do CDN no sample do po-page-login

2022-08-19 01:22 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-background-color-container-on: var(--track-checked);
está pegando a customização na 'key', era para pegar somente na 'track'.

2022-08-19 01:22 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-background-color-container-disabled: var(--track-unchecked);
está pegando a customização na 'key', era para pegar somente na 'track'.

2022-08-19 01:22 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
>    --color-switch-background-color-button-disabled: var(--color-neutral-light-40);
não pegou a customização

2022-08-19 01:23 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-color-icon-disabled: var(--color-neutral-light-00);
não pegou a customização

2022-08-19 01:29 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --track-checked: var(--color-brand-01-light);
necessário utilizar as variáveis secondary...

2022-08-19 01:31 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-checked-disabled: var(--color-action-disabled);
necessário utilizar as variáveis --color-secondary... para manter a customização existente, elas estão apontando para a customização dos tokens de marca

2022-08-19 01:38 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --track-unchecked: var(--color-neutral-light-20);
a customização pegou também no checked.

2022-08-19 01:39 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-checked-disabled: var(--color-action-disabled);
a customização pegou na borda do unchecked e pegou na label

2022-08-19 21:46 UTC, jribeiroo approved these changes

2022-08-19 22:04 UTC, gabrielibarbosa approved these changes

2022-08-19 23:35 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-background-color-container-on: var(--track-checked); /*Deprecated v16.x.x utilizar -track-checked */
a customização através dessa variável contina pegando na key e era para pegar somente na track

2022-08-19 23:36 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-background-color-container-disabled: var(
--color-switch-background-color-container-disabled - > a customização através dessa variável está pegando na key e era para pegar somente na track

2022-08-19 23:36 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-background-color-button-disabled: var(
--color-switch-background-color-button-disabled ->. a customização através dessa variável não está funcionando

2022-08-19 23:37 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-switch-color-icon-disabled: var(--color-unchecked); /*Deprecated v16.x.x utilizar --color-unchecked */
--color-switch-color-icon-disabled -> a customização através dessa variável não está funcionando.

2022-08-19 23:38 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-checked-disabled: var(--color-action-disabled);
essas variáveis devem referenciar a variável --color-secondary e suas variações, não deve referenciar os tokens de marca.

2022-08-19 23:40 UTC, alinelariguet requested changes
Necessário ajustes para customização.

2022-08-31 12:02 UTC, gabrielibarbosa submitted a review, later dismissed

2022-09-02 19:51 UTC, gabrielibarbosa approved these changes

2022-09-02 19:54 UTC, jribeiroo approved these changes

2022-09-02 19:58 UTC, alinelariguet approved these changes

2022-09-02 19:58 UTC, merged