Textarea/DTHFUI-6442
po-ui/po-style pull request #340
Opened 2022-09-08 21:57 UTC by brunoromeiro

Aplica estilo definido pelo AnimaliaDS

Fixes DTHFUI-6442

2022-09-15 20:16 UTC, rafaellmarques approved these changes

2022-09-15 20:16 UTC, jcorrea97 approved these changes

2022-09-25 17:04 UTC, alinelariguet commented
estava com conflito na branch, ajustei precisa aprovar novamente.

2022-09-25 17:16 UTC, jcorrea97 submitted a review, later dismissed

2022-09-25 17:22 UTC, alinelariguet commented on src/css/themes/po-theme-default.css
> +  --color-error: var(--color-feedback-negative-base);
deve aplicar as variáveis legacy. Ex: --color-secondary no lugar de --color-action-default. Verificar da linha 1435 até 1453.

2022-09-25 17:26 UTC, alinelariguet requested changes
verificar comentários anteriores.

2022-09-25 21:43 UTC, alinelariguet approved these changes

2022-09-25 22:40 UTC, jcorrea97 approved these changes

2022-09-25 22:41 UTC, merged