feat(combo): adiciona a propriedade p-clean
po-ui/po-style pull request #70
Opened 2019-12-28 20:13 UTC by diegoalexandrooliveira

Adiciona a classe po-field-second-icon-container-right
para o combo comportar 2 ícones

Fixes DTHFUI-2314, #152

2020-02-06 12:35 UTC, mateusjmaf commented on src/css/components/po-field/po-field-icon/po-field-icon.css
> +
Verificar comentário em https://github.com/portinariui/portinari-angular/pull/213/files#r375808661.

2020-02-06 12:36 UTC, mateusjmaf commented on src/css/components/po-field/po-field-icon/po-field-icon.css
> +.po-field-icon-container-right,
Diego, favor adicionar um exemplo de uso no arquivo `html`.

2020-09-04 14:58 UTC, jhosefmarks requested changes
Necessário atualizar PR.

2020-09-08 18:07 UTC, diegoalexandrooliveira commented
Favor desconsiderar o PR, já existe uma classe que exibe dois ícones a direita.

2020-09-08 18:07 UTC, closed without merging